### PR TITLE
changing array allocation from c99 to c++0x conventions

### LINKED ISSUE #121: Variable Length Array Issue
There are 2 files (there may be more):

sequenceDiversity.cpp
hapLrt.cpp

that use this form of array allocation:

string haplotypes [nsamples][2];

The C11 compiler is throwing a compile-time error on these lines:

c++: Error: variable length array of non-POD element type

It appears that the variable array allocation syntax is only valid in C99 and was not adopted in later versions. Check out this discussion for more information on the topic.

https://groups.google.com/forum/#!topic/comp.std.c++/K_4lgA1JYeg

### PR DESCRIPTION
**Pull request by nh13**
Fixes #121 @ekg

### CODE REVIEW

File: src/plotHaps.cpp [hunk 1]
```diff
@@ -57,7 +57,7 @@ void loadIndices(map<int, int> & index, string set){
   }
 }
 
-void calc(string haplotypes[][2], int nhaps, vector<double> afs, vector<long int> pos, vector<int> & target, vector<int> & background, string seqid){
+void calc(string **haplotypes, int nhaps, vector<double> afs, vector<long int> pos, vector<int> & target, vector<int> & background, string seqid){
```
Comment (nh13) [inline src/plotHaps.cpp:60]: @ekg so much code duplication!

**Comment by zeeev** [comment]
Thank you, @nh13. I really need a haplotype class.  I was learning CPP when i wrote this code. 

I will duplicate your fixes here:

https://github.com/vcflib/vcflib
